Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Копируем пустой файл в домашнюю директорию пользователя vagrant
  config.vm.provision "file", source: "my_empty_file.txt", destination: "/home/vagrant/my_empty_file.txt"

  # Устанавливаем необходимые пакеты и Python-библиотеки
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip python3-dev libpq-dev
    pip3 install psycopg2 Django
  SHELL
end
